### ISSUE TITLE
question

### ISSUE THREAD

**Issue by MaraScott** [jojomi/docker-pageres#1]
Hi,
I runned this below command with your nice container : 
```shell
pageres https://www.studio-cyclone.com/my-quest.php https://www.davaskweblimited.com/ https://www.google.com/  375x667
```
But I got this results : 
https://www.studio-cyclone.com/my-quest.php
![studio-cyclone com take-payment php offer 3-welcome-375x667](https://user-images.githubusercontent.com/482210/33481692-eda2fdbc-d695-11e7-8aca-08ec71bcd17d.png)

https://www.davaskweblimited.com/
![davaskweblimited com-667x375](https://user-images.githubusercontent.com/482210/33481701-fd4627ee-d695-11e7-9cfa-45800907feb9.png)

https://www.google.com/
![google com-375x667](https://user-images.githubusercontent.com/482210/33481696-f2b036c6-d695-11e7-946c-708ed178e215.png)

Do you know why I have a weird display on the first page and not the others ? 

How can I debug that ?

Best regards,

david

**Comment by jojomi** [comment]
I think that is rather an issue for https://github.com/sindresorhus/pageres. Perhaps you can try to render it with other resolutions or different timeouts.
